import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/globals/Navbar'
import Provider from '@/components/globals/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen font-sans antialiased grainy',inter.className)}>
        <Provider>
         <main>
            <Navbar />
            {children}
         </main>
        </Provider>
      </body>
    </html>
  )
}
